### ISSUE TITLE
Hyperparameters selection

### ISSUE THREAD

**Issue by leo2105** [phamquiluan/ResidualMaskingNetwork#10]
Nice contribution, I am using in my master program, obviously im gonna cite you.

How did you find the best hyperparameters which are found in config? For example for fer_2013, its ok if I only change the arch name or should I change for example lr or max_iter or batch etc?

I ran your implementation and I got 73.06 no 74.14

**Comment by phamquiluan** [comment]
@leo2105 Sorry for this late reply, 

Thank you for this question! Hmm, first of all, I should confirm with you that, I don't perform hyperparameters searching. I use the fixed hyperparameters set from the beginning to ensure that the experiments are fair.

Btw, my paper has been accepted at ICPR 2020 :joy: 
![image](https://user-images.githubusercontent.com/24642166/85257341-e4ca2f00-b48f-11ea-912f-bf9430e1ca83.png)

**Comment by phamquiluan** [comment]
@leo2105 about your 73.06, are you load the resnet34 pre-trained weights from the beginning?

**Comment by leo2105** [comment]
yeah, actually I had seen #7 and trained, maybe the seeds that you used work different on each ubuntu distribution or pytorch version, idk exactly. 
I will try other hyper-parameters, and other implementation trying to overpass your results hehe, thats my goal in this area.

About ICPR acceptance, thats so impressive, congratulations, I had a poster in a LatinX in AI workshop in NeurIPS in 2018, I went there and I was so exciting about all the works, talks and events. I hope you go. GL!
So, I will cite a ICPR paper, NICE!

btw, your model is heavy, 8GB video compared to other ones pretrained in torch. hehe

**Comment by jet-yangqs** [comment]
I search your paper with the name posted above, but I don't find it. Can you upload it or share a link to your paper? thank you~

**Comment by xiaoroulian** [comment]
> I search your paper in google with the name posted above, but I can't find it. Can you upload it or share a link to your paper? thank you~

So do I

**Comment by patilabhijit007** [comment]
Request you to kindly upload the paper. The entire thesis is a bit difficult to understand.
Thank you

**Comment by phamquiluan** [comment]
here you are
https://ieeexplore.ieee.org/abstract/document/9411919
