### ISSUE TITLE
How many params does Resmasking50 have?

### ISSUE THREAD

**Issue by heraclex12** [phamquiluan/ResidualMaskingNetwork#11]
Hi,

As your dissertation, Resmasking (resnet34 base) model has 149m params. So do you know how many params does resmasking50 have? I got 1.8 billions for it, too big, I want to make sure my result is correct.

And do you use pre-trained weights for resmasking50? If yes, which's one?

I saw your submission was accepted, congratulations! I am student from Vietnam, can I get your contact to ask some questions and learn from your experience?

Thank you so much!

**Comment by phamquiluan** [comment]
sorry for late response, hmm, I did not calc the number of resmasking 50 parameters.
You can do it yourself by using some libs like `torchsummary` :pray:
