### ISSUE TITLE
How to use it to train more or less than 7 emotions?

### ISSUE THREAD

**Issue by srushti108** [phamquiluan/ResidualMaskingNetwork#12]
Hii,
I tried your's model for prediction , it gives much better result for the 7 classes in fer2013.
But, I want to use it to train on more 5 emotion classes .
For now, I was trying with one less class, I did conversion of my 6 classes data to the fer data format and make change num_classes=6 in fer2013_config and tried with default 'alexnet' model. 
Training is on, till now it's running without error.
But, is that sufficient changes? Or Is it possible to train for more classes in this way? 
(Is there any changes require in tta_trainer.py or alexnet.py ?)
Please help me to clarify with this.

**Comment by phamquiluan** [comment]
I did exp in this case yet, but, it should be ok.
if it's not, try to update the last fully-connected layer configuration :pray:
