### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Gauravajariwal11** [phamquiluan/ResidualMaskingNetwork#15]
getting this error when i run python ssd_infer.py. Any suggestions? 

RuntimeError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 10.76 GiB total capacity; 996.23 MiB already allocated; 8.81 MiB free; 1010.00 MiB reserved in total by PyTorch)

**Comment by phamquiluan** [comment]
There may be other programs that consume you GPU RAM.
