### ISSUE TITLE
Image for analyse wrong cases in FER2013

### ISSUE THREAD

**Issue by phamquiluan** [phamquiluan/ResidualMaskingNetwork#2]
Image for analyse wrong cases in FER2013

https://drive.google.com/open?id=1UYZAlQA9rPzxhs-72nYsOx2iiTEG6sSE

mainly for wrongly labelling or emotional intensity

**Comment by liujinTyler** [comment]
作者你好，我申请了访问，麻烦通过一下，谢谢！
Hello, the author, I have applied for an interview, please pass it, thank you!
