### ISSUE TITLE
how to cite your ICPR2020 paper?

### ISSUE THREAD

**Issue by jet-yangqs** [phamquiluan/ResidualMaskingNetwork#20]
Hello, how to cite your paper published in ICPR2020 ? It seems that google scholar can't find this paper.

**Comment by phamquiluan** [comment]
L. Pham, H. Vu, T. A. Tran, "Facial Expression Recognition Using Residual Masking Network", IEEE 25th International Conference on Pattern Recognition, 2020, 4513-4519. Milan -Italia.

bibtex:
```
@inproceedings{luanresmaskingnet2020,
  title={Facial Expression Recognition using Residual Masking Network},
  author={Luan, Pham and Huynh, Vu and Tuan Anh, Tran},
  booktitle={IEEE 25th International Conference on Pattern Recognition},
  pages={4513--4519},
  year={2020}
}```

**Comment by phamquiluan** [comment]
https://ieeexplore.ieee.org/abstract/document/9411919
