### ISSUE TITLE
some demo images

### ISSUE THREAD

**Issue by phamquiluan** [phamquiluan/ResidualMaskingNetwork#3]

**Comment by phamquiluan** [comment]
![matbiec_1864](https://user-images.githubusercontent.com/24642166/72135683-acd79f80-33b9-11ea-911a-876b760f35d0.png)
![matbiec_1919](https://user-images.githubusercontent.com/24642166/72135684-acd79f80-33b9-11ea-8683-20e857bcfcb5.png)
![ngoctrinh](https://user-images.githubusercontent.com/24642166/72135685-acd79f80-33b9-11ea-8cee-823ac37c60cf.png)

**Comment by phamquiluan** [comment]
![matbiec_1706](https://user-images.githubusercontent.com/24642166/72135702-b7923480-33b9-11ea-81a5-9014aa3d12bb.png)
![matbiec_1707](https://user-images.githubusercontent.com/24642166/72135703-b7923480-33b9-11ea-9fca-fe9106bee820.png)
![matbiec_1708](https://user-images.githubusercontent.com/24642166/72135705-b82acb00-33b9-11ea-990d-f05f0e97145f.png)
![matbiec_1810](https://user-images.githubusercontent.com/24642166/72135706-b82acb00-33b9-11ea-98b3-77353a1213f5.png)
![matbiec_1833](https://user-images.githubusercontent.com/24642166/72135707-b82acb00-33b9-11ea-8535-9e9ed6f4e8cb.png)

**Comment by phamquiluan** [comment]
![matbiec_733](https://user-images.githubusercontent.com/24642166/72135725-c4168d00-33b9-11ea-96a5-da692fd3ee2f.png)
![matbiec_1171](https://user-images.githubusercontent.com/24642166/72135727-c4168d00-33b9-11ea-8948-5d77ebcb7f6b.png)
![matbiec_1183](https://user-images.githubusercontent.com/24642166/72135728-c4af2380-33b9-11ea-9102-d7dc2f06ca27.png)
![matbiec_1185](https://user-images.githubusercontent.com/24642166/72135729-c4af2380-33b9-11ea-9a0e-cfe5855b49ae.png)
![matbiec_1189](https://user-images.githubusercontent.com/24642166/72135731-c547ba00-33b9-11ea-8b7c-a7314520a101.png)
![matbiec_1190](https://user-images.githubusercontent.com/24642166/72135732-c547ba00-33b9-11ea-8a06-4e506fdf9657.png)
![matbiec_1191](https://user-images.githubusercontent.com/24642166/72135734-c547ba00-33b9-11ea-8690-35a36497bbcb.png)

**Comment by phamquiluan** [comment]
![harry1_8911](https://user-images.githubusercontent.com/24642166/72135767-d8f32080-33b9-11ea-9caa-a213fbf75de6.png)
![harry1_11519](https://user-images.githubusercontent.com/24642166/72135768-d8f32080-33b9-11ea-88a2-25ac374bdf69.png)
![harry1_60140](https://user-images.githubusercontent.com/24642166/72135771-d98bb700-33b9-11ea-935b-41ca437b8941.png)
![harry1_61764](https://user-images.githubusercontent.com/24642166/72135772-d98bb700-33b9-11ea-90ef-a2206cd451e6.png)
![harry1_61765](https://user-images.githubusercontent.com/24642166/72135775-d98bb700-33b9-11ea-8f94-1862cdb25a9d.png)
![matbiec4](https://user-images.githubusercontent.com/24642166/72135777-da244d80-33b9-11ea-90ee-706b25c0a5a9.png)

**Comment by phamquiluan** [comment]
![emma2](https://user-images.githubusercontent.com/24642166/72135796-e4dee280-33b9-11ea-93b3-384c6ad843b1.jpg)
![harry1_7683](https://user-images.githubusercontent.com/24642166/72135797-e4dee280-33b9-11ea-8320-34520c1971dc.png)
![harry1_7684](https://user-images.githubusercontent.com/24642166/72135799-e5777900-33b9-11ea-85d4-202cd7846f0c.png)
![harry1_7707](https://user-images.githubusercontent.com/24642166/72135800-e5777900-33b9-11ea-86c8-a5a14a4cf199.png)
![harry1_7708](https://user-images.githubusercontent.com/24642166/72135801-e5777900-33b9-11ea-9886-7004d6a08cbf.png)
![harry1_8910](https://user-images.githubusercontent.com/24642166/72135802-e6100f80-33b9-11ea-996b-5d302ca3f1df.png)

**Comment by phamquiluan** [comment]
![localhost_6006_](https://user-images.githubusercontent.com/24642166/75408653-fddf2b00-5948-11ea-981f-3d95478d5708.png)

**Comment by Droid021** [comment]
How were these generated exactly? @phamquiluan

**Comment by phamquiluan** [comment]
![full_flow_7_revised_page-0001](https://github.com/phamquiluan/ResidualMaskingNetwork/assets/24642166/5ccb5a2d-e79b-4fd3-b60f-c7d22ce1285d)

**Comment by phamquiluan** [comment]
![full_flow_7_revised_page-0001 (1)](https://github.com/phamquiluan/ResidualMaskingNetwork/assets/24642166/ee2909f0-f084-47bb-8262-2c1728166fba)
