### ISSUE TITLE
Issue when using m.draw

### ISSUE THREAD

**Issue by DaddyWesker** [phamquiluan/ResidualMaskingNetwork#32]
Hello.

THank you for your code. I've installed your rmn with `pip install rmn`. It works fine when i'm using this 

```
video_capture = cv2.VideoCapture(0)
m = RMN()
_, frame = video_capture.read()
results = m.detect_emotion_for_single_frame(frame)
frame = m.draw(frame, results)
```

But, i've wanted to try using your model with pre-detected face image (since i'll probably use another face detector). SO, for that case i've changed code like this

```
video_capture = cv2.VideoCapture(0)
m = RMN()
_, frame = video_capture.read()

face = m.detect_faces(frame)
xmin = face[0]["xmin"]
ymin = face[0]["ymin"]
xmax = face[0]["xmax"]
ymax = face[0]["ymax"]

frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
face_image = frame[ymin:ymax, xmin:xmax]
results = m.detect_emotion_for_single_face_image(face_image)
frame = m.draw(frame, results)
```

And i've got error on m.draw
```

Traceback (most recent call last):
  File "/home/daddywesker/EmotionRecognition/RMN/testing_rmn.py", line 20, in <module>
    frame = m.draw(frame, results)
  File "/home/daddywesker/anaconda3/envs/rmn/lib/python3.7/site-packages/rmn/__init__.py", line 208, in draw
    xmin = r["xmin"]
TypeError: string indices must be integers

Process finished with exit code 1
```
which is kinda understandable, since `result` in that case doesn't contain all the necessary fields for drawing and it's structure is slightly different. So, maybe you should add some "if" check to avoid that error? Or just let now user what he should send to m.draw.

**Comment by phamquiluan** [comment]
@DaddyWesker Thank you for reporting the issue, I've pushed some docstring, hope it helps :joy:

**Comment by phamquiluan** [comment]
https://github.com/phamquiluan/ResidualMaskingNetwork/commit/b77abb6e548b9a09b5c96b1592d71332b45d050e

**Comment by DaddyWesker** [comment]
Great, thanks =)

**Comment by phamquiluan** [comment]
@DaddyWesker one star please =))))

**Comment by DaddyWesker** [comment]
=) Done
