### ISSUE TITLE
How to get the model once it has been trained

### ISSUE THREAD

**Issue by Daniel-CG-Wright** [phamquiluan/ResidualMaskingNetwork#50]
Hi,
I have trained the model by running main_fer2013.py and it successfully did the training (after adding the fer dataset to saved/ etc)
However, how can I then use the model to predict images once the model is trained? I see it created a file in checkpoints/ dir, but I am not sure how to use this.

Thank you

**Comment by phamquiluan** [comment]
You can check this file to see if it helps: https://github.com/phamquiluan/ResidualMaskingNetwork/blob/master/legacy/demo_one_image.py

**Comment by Daniel-CG-Wright** [comment]
Thank you for the fast response, this helps!
