### ISSUE TITLE
sửa lại citation như ở dưới nhé

### ISSUE THREAD

**Issue by teppialy** [phamquiluan/ResidualMaskingNetwork#6]
@misc{luanresmaskingnet2020,
	Author = {Luan Pham & Tuan Anh Tran},
	Title = {Facial Expression Recognition using Residual Masking Network},
	url = {https://github.com/phamquiluan/ResidualMaskingNetwork},
	Year = {2020}
}

**Comment by phamquiluan** [comment]
dạ rồi thầy :v
